apiVersion: v2
name: tor-snowflake-proxy
description: A Helm chart for running a Tor Snowflake proxy in Kubernetes cluster to help censored users connect to the Tor network.
type: application
version: 0.1.0
appVersion: "v2.11.0"
icon: https://styleguide.torproject.org/static/images/tor-browser/stable/stable.svg
maintainers:
  - name: cloudwithdan
    email: nikoloskid@pm.me
sources:
  - https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake
  - https://snowflake.torproject.org/
keywords:
  - tor
  - snowflake
  - proxy
  - privacy
  - censorship
